# Dependecies

In [1]:
import numpy as np
import pandas as pd
import requests
import time
import json
from pprint import pprint
import xml.etree.ElementTree as ET
from collections import OrderedDict

In [2]:
import sqlalchemy
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect
from cryptography.fernet import Fernet

# NYT Data Extract/Transform

In [3]:
# API KEY 
ses_api_key = "EH3LYl2x8c4wLClt63RJZGBrZboUE507"

# Best Sellers Lists
nyt_lists_qry = "https://api.nytimes.com/svc/books/v3/lists/names.json?api-key=" + ses_api_key 
nyt_lists_results = requests.get(nyt_lists_qry).json()
nyt_lists_results
nyt_lists_df = pd.DataFrame(nyt_lists_results['results'])

In [4]:
nyt_lists_df.sort_values(['newest_published_date'], ascending = False)

,display_name,list_name,list_name_encoded,newest_published_date,oldest_published_date,updated
0,Combined Print & E-Book Fiction,Combined Print and E-Book Fiction,combined-print-and-e-book-fiction,2019-09-01,2011-02-13,WEEKLY
11,"Advice, How-To & Miscellaneous",Advice How-To and Miscellaneous,advice-how-to-and-miscellaneous,2019-09-01,2013-04-28,WEEKLY
1,Combined Print & E-Book Nonfiction,Combined Print and E-Book Nonfiction,combined-print-and-e-book-nonfiction,2019-09-01,2011-02-13,WEEKLY
24,Children’s Series,Series Books,series-books,2019-09-01,2008-06-08,WEEKLY
23,Children’s Picture Books,Picture Books,picture-books,2019-09-01,2008-06-08,WEEKLY
20,Children’s Middle Grade Hardcover,Childrens Middle Grade Hardcover,childrens-middle-grade-hardcover,2019-09-01,2015-08-30,WEEKLY
27,Young Adult Hardcover,Young Adult Hardcover,young-adult-hardcover,2019-09-01,2015-08-30,WEEKLY
6,Paperback Nonfiction,Paperback Nonfiction,paperback-nonfiction,2019-09-01,2008-06-08,WEEKLY
2,Hardcover Fiction,Hardcover Fiction,hardcover-fiction,2019-09-01,2008-06-08,WEEKLY
3,Hardcover Nonfiction,Hardcover Nonfiction,hardcover-nonfiction,2019-09-01,2008-06-08,WEEKLY
4,Paperback Trade Fiction,Trade Fiction Paperback,trade-fiction-paperback,2019-09-01,2008-06-08,WEEKLY
31,Audio Nonfiction,Audio Nonfiction,audio-nonfiction,2019-08-18,2018-03-11,MONTHLY
53,Sports and Fitness,Sports,sports,2019-08-18,2014-03-02,MONTHLY
52,Science,Science,science,2019-08-18,2013-04-14,MONTHLY
32,Business,Business Books,business-books,2019-08-18,2013-11-03,MONTHLY
30,Audio Fiction,Audio Fiction,audio-fiction,2019-08-18,2018-03-11,MONTHLY
21,Children’s Middle Grade Paperback,Childrens Middle Grade Paperback,childrens-middle-grade-paperback,2017-01-29,2015-08-30,WEEKLY
8,E-Book Nonfiction,E-Book Nonfiction,e-book-nonfiction,2017-01-29,2011-02-13,WEEKLY
28,Young Adult Paperback,Young Adult Paperback,young-adult-paperback,2017-01-29,2015-08-30,WEEKLY
26,Young Adult E-Book,Young Adult E-Book,young-adult-e-book,2017-01-29,2015-08-30,WEEKLY
7,E-Book Fiction,E-Book Fiction,e-book-fiction,2017-01-29,2011-02-13,WEEKLY
5,Paperback Mass-Market Fiction,Mass Market Paperback,mass-market-paperback,2017-01-29,2008-06-08,WEEKLY
19,Children’s Middle Grade E-Book,Childrens Middle Grade E-Book,childrens-middle-grade-e-book,2017-01-29,2015-08-30,WEEKLY
14,Manga,Manga,manga,2017-01-29,2009-03-15,WEEKLY
13,Paperback Graphic Books,Paperback Graphic Books,paperback-graphic-books,2017-01-29,2009-03-15,WEEKLY
12,Hardcover Graphic Books,Hardcover Graphic Books,hardcover-graphic-books,2017-01-29,2009-03-15,WEEKLY
37,Espionage,Espionage,espionage,2017-01-15,2014-12-14,MONTHLY
51,"Religion, Spirituality and Faith",Religion Spirituality and Faith,religion-spirituality-and-faith,2017-01-15,2014-09-07,MONTHLY
50,Race and Civil Rights,Race and Civil Rights,race-and-civil-rights,2017-01-15,2014-12-14,MONTHLY
49,Politics and American History,Hardcover Political Books,hardcover-political-books,2017-01-15,2011-07-03,MONTHLY
48,Parenthood and Family,Family,family,2017-01-15,2014-09-07,MONTHLY
46,Love and Relationships,Relationships,relationships,2017-01-15,2014-09-07,MONTHLY
44,Humor,Humor,humor,2017-01-15,2014-09-07,MONTHLY
43,Health,Health,health,2017-01-15,2014-10-12,MONTHLY
41,Games and Activities,Games and Activities,games-and-activities,2017-01-15,2014-10-12,MONTHLY
40,Food and Diet,Food and Fitness,food-and-fitness,2017-01-15,2013-09-01,MONTHLY
39,"Fashion, Manners and Customs",Fashion Manners and Customs,fashion-manners-and-customs,2017-01-15,2014-10-12,MONTHLY
38,Expeditions,Expeditions Disasters and Adventures,expeditions-disasters-and-adventures,2017-01-15,2014-12-14,MONTHLY
54,Travel,Travel,travel,2017-01-15,2014-09-07,MONTHLY
35,Culture,Culture,culture,2017-01-15,2014-10-12,MONTHLY
34,Crime and Punishment,Crime and Punishment,crime-and-punishment,2017-01-15,2014-10-12,MONTHLY
33,Celebrities,Celebrities,celebrities,2017-01-15,2014-09-07,MONTHLY
29,Animals,Animals,animals,2017-01-15,2014-09-07,MONTHLY
36,Education,Education,education,2017-01-15,2014-10-12,MONTHLY
45,Indigenous Americans,Indigenous Americans,indigenous-americans,2016-01-10,2014-12-14,MONTHLY
25,Young Adult,Young Adult,young-adult,2015-08-23,2012-12-16,WEEKLY
18,Children’s Middle Grade,Childrens Middle Grade,childrens-middle-grade,2015-08-23,2012-12-16,WEEKLY
42,Hardcover Business Books,Hardcover Business Books,hardcover-business-books,2013-10-13,2011-07-03,MONTHLY
47,Paperback Business Books,Paperback Business Books,paperback-business-books,2013-10-13,2011-07-03,MONTHLY
15,Combined Hardcover & Paperback Fiction,Combined Print Fiction,combined-print-fiction,2013-05-12,2011-02-13,WEEKLY
16,Combined Hardcover & Paperback Nonfiction,Combined Print Nonfiction,combined-print-nonfiction,2013-05-12,2011-02-13,WEEKLY
10,Paperback Advice & Misc.,Paperback Advice,paperback-advice,2013-04-21,2008-06-08,WEEKLY
9,Hardcover Advice & Misc.,Hardcover Advice,hardcover-advice,2013-04-21,2008-06-08,WEEKLY
17,Children’s Chapter Books,Chapter Books,chapter-books,2012-12-09,2008-06-08,WEEKLY
22,Children’s Paperback Books,Paperback Books,paperback-books,2012-12-09,2008-06-08,WEEKLY

In [5]:
# Hardcover NONFiction Best Sellers Extract
nyt_h_nfiction_qry = "https://api.nytimes.com/svc/books/v3/lists/current/hardcover-nonfiction.json?api-key=" + ses_api_key 
nyt_h_nfiction_results = requests.get(nyt_h_nfiction_qry).json()
nyt_h_nfiction_results
nyt_h_nfiction = nyt_h_nfiction_results['results']['books']

In [6]:
# Hardcover NONFiction Transform
nyt_h_nf_df = pd.DataFrame(nyt_h_nfiction)
nyt_h_nf_df = nyt_h_nf_df[['rank','weeks_on_list', 'primary_isbn13', 'publisher', 'book_review_link']]
nyt_h_nf_df = nyt_h_nf_df.rename(columns={'primary_isbn13':'book_id'})
nyt_h_nf_df['book_id']=nyt_h_nf_df['book_id'].astype(np.int64)



category = 'Hardcover Non-Fiction'
nyt_h_nf_df['category'] = category
date = pd.datetime.now()
nyt_h_nf_df['current_as_of_date'] = date

nyt_h_nf_df.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
0,1,78,9780399590504,Random House,https://www.nytimes.com/2018/03/01/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
1,2,1,9780525509288,One World,,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
2,3,40,9781524763138,Crown,https://www.nytimes.com/2018/12/06/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
3,4,6,9781451642292,Avid Reader,https://www.nytimes.com/2019/06/28/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
4,5,15,9781501168680,Simon & Schuster,https://www.nytimes.com/2019/05/13/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962

In [7]:
# Paperback NONFiction Best Sellers
nyt_p_nfiction_qry = "https://api.nytimes.com/svc/books/v3/lists/current/paperback-nonfiction.json?api-key=" + ses_api_key 
nyt_p_nfiction_results = requests.get(nyt_p_nfiction_qry).json()
nyt_p_nfiction_results
nyt_p_nfiction = nyt_p_nfiction_results['results']['books']

In [8]:
# Paperback NONFiction Transform
nyt_p_nf_df = pd.DataFrame(nyt_p_nfiction)
nyt_p_nf_df = nyt_p_nf_df[['rank','weeks_on_list', 'primary_isbn13', 'publisher', 'book_review_link']]
nyt_p_nf_df = nyt_p_nf_df.rename(columns={'primary_isbn13':'book_id'})
nyt_p_nf_df['book_id']=nyt_p_nf_df['book_id'].astype(np.int64)

category = 'Paperback Non-Fiction'
nyt_p_nf_df['category'] = category
date = pd.datetime.now()
nyt_p_nf_df['current_as_of_date'] = date

nyt_p_nf_df.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
0,1,27,9780399588198,Spiegel & Grau,,Paperback Non-Fiction,2019-08-23 17:08:53.913316
1,2,66,9780062316110,Harper Perennial,,Paperback Non-Fiction,2019-08-23 17:08:53.913316
2,3,58,9780807047415,Beacon Press,,Paperback Non-Fiction,2019-08-23 17:08:53.913316
3,4,166,9780812984965,Spiegel & Grau,,Paperback Non-Fiction,2019-08-23 17:08:53.913316
4,5,43,9780143127741,Penguin,,Paperback Non-Fiction,2019-08-23 17:08:53.913316

In [9]:
# Hardcover Fiction Best Sellers
nyt_h_fiction_qry = "https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=" + ses_api_key 
nyt_h_fiction_results = requests.get(nyt_h_fiction_qry).json()
nyt_h_fiction_results
nyt_h_fiction = nyt_h_fiction_results['results']['books']

In [10]:
# Hardcover Fiction Transform
nyt_h_f_df = pd.DataFrame(nyt_h_fiction)
nyt_h_f_df = nyt_h_f_df[['rank','weeks_on_list', 'primary_isbn13', 'publisher', 'book_review_link']]
nyt_h_f_df = nyt_h_f_df.rename(columns={'primary_isbn13':'book_id'})
nyt_h_f_df['book_id']=nyt_h_f_df['book_id'].astype(np.int64)

category = 'Hardcover Fiction'
nyt_h_f_df['category'] = category
date = pd.datetime.now()
nyt_h_f_df['current_as_of_date'] = date

nyt_h_f_df.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
0,1,50,9780735219090,Putnam,,Hardcover Fiction,2019-08-23 17:08:57.592794
1,2,2,9780316527583,"Little, Brown",,Hardcover Fiction,2019-08-23 17:08:57.592794
2,3,1,9781250051059,Minotaur,,Hardcover Fiction,2019-08-23 17:08:57.592794
3,4,4,9781538750568,Grand Central,,Hardcover Fiction,2019-08-23 17:08:57.592794
4,5,5,9780385537070,Doubleday,https://www.nytimes.com/2019/07/11/books/revie...,Hardcover Fiction,2019-08-23 17:08:57.592794

In [11]:
# Trade Fiction Paperback Best Sellers
nyt_tfp_qry = "https://api.nytimes.com/svc/books/v3/lists/current/trade-fiction-paperback.json?api-key=" + ses_api_key 
nyt_tfp_results = requests.get(nyt_tfp_qry).json()
nyt_tfp_results
nyt_tfp = nyt_tfp_results['results']['books']

In [12]:
# Trade Fiction Paperback Transform
nyt_tfp_df = pd.DataFrame(nyt_tfp)
nyt_tfp_df = nyt_tfp_df[['rank','weeks_on_list', 'primary_isbn13', 'publisher', 'book_review_link']]
nyt_tfp_df = nyt_tfp_df.rename(columns={'primary_isbn13':'book_id'})
nyt_tfp_df['book_id']=nyt_tfp_df['book_id'].astype(np.int64)

category = 'Trade Fiction Paperback'
nyt_tfp_df['category'] = category
date = pd.datetime.now()
nyt_tfp_df['current_as_of_date'] = date

nyt_tfp_df.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
0,1,164,9780062364913,Harper Perennial,,Trade Fiction Paperback,2019-08-23 17:09:00.664423
1,2,50,9780062797155,Harper,https://www.nytimes.com/2018/11/16/books/revie...,Trade Fiction Paperback,2019-08-23 17:09:00.664423
2,3,15,9780735224315,Penguin,https://www.nytimes.com/2017/09/25/books/revie...,Trade Fiction Paperback,2019-08-23 17:09:00.664423
3,4,2,9781400033416,Vintage,https://www.nytimes.com/1987/09/02/books/books...,Trade Fiction Paperback,2019-08-23 17:09:00.664423
4,5,13,9780425284704,Ballantine,,Trade Fiction Paperback,2019-08-23 17:09:00.664423

In [13]:
# YA Hardcover Best Sellers
nyt_ya_qry = "https://api.nytimes.com/svc/books/v3/lists/current/young-adult-hardcover.json?api-key=" + ses_api_key 
nyt_ya_results = requests.get(nyt_ya_qry).json()
nyt_ya_results
nyt_ya = nyt_ya_results['results']['books']

In [14]:
# YA Hardcover Transform
nyt_ya_df = pd.DataFrame(nyt_ya)
nyt_ya_df = nyt_ya_df[['rank','weeks_on_list', 'primary_isbn13', 'publisher', 'book_review_link']]
nyt_ya_df = nyt_ya_df.rename(columns={'primary_isbn13':'book_id'})
nyt_ya_df['book_id']=nyt_ya_df['book_id'].astype(np.int64)

category = 'YA Hardcover'
nyt_ya_df['category'] = category
date = pd.datetime.now()
nyt_ya_df['current_as_of_date'] = date

nyt_ya_df.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
0,1,129,9780062498533,Balzer + Bray,,YA Hardcover,2019-08-23 17:09:02.770294
1,2,37,9781534451568,Simon & Schuster,,YA Hardcover,2019-08-23 17:09:02.770294
2,3,17,9780062662804,HarperTeen,,YA Hardcover,2019-08-23 17:09:02.770294
3,4,76,9781250170972,Holt,,YA Hardcover,2019-08-23 17:09:02.770294
4,5,87,9781524714680,Delacorte,,YA Hardcover,2019-08-23 17:09:02.770294

In [15]:
nyt_books = pd.concat([nyt_h_nf_df, nyt_p_nf_df, nyt_h_f_df, nyt_tfp_df, nyt_ya_df]).reset_index()
del nyt_books['index']
nyt_books.index.name = 'reviews_id'
nyt_books.head()

,rank,weeks_on_list,book_id,publisher,book_review_link,category,current_as_of_date
reviews_id,,,,,,,
0,1,78,9780399590504,Random House,https://www.nytimes.com/2018/03/01/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
1,2,1,9780525509288,One World,,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
2,3,40,9781524763138,Crown,https://www.nytimes.com/2018/12/06/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
3,4,6,9781451642292,Avid Reader,https://www.nytimes.com/2019/06/28/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962
4,5,15,9781501168680,Simon & Schuster,https://www.nytimes.com/2019/05/13/books/revie...,Hardcover Non-Fiction,2019-08-23 17:08:51.622962

# Goodreads Data Extract/Transform

In [16]:
# Import CSV

books_csv = "books.csv"
booksdata = pd.read_csv(books_csv, error_bad_lines=False)
booksdata.head()

b'Skipping line 4012: expected 10 fields, saw 11\nSkipping line 5688: expected 10 fields, saw 11\nSkipping line 7056: expected 10 fields, saw 11\nSkipping line 10601: expected 10 fields, saw 11\nSkipping line 10668: expected 10 fields, saw 11\n'

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré,4.55,043965548X,9780439655484,eng,435,2149872,33964

In [17]:
# Clean database (booksID from isbn13, title, authors)

booksDB = booksdata[["isbn13", "title", "authors"]]
booksDB = booksDB.rename(columns={"isbn13": "book_id",
                                    "title": "title",
                                    "authors": "authors"})
booksDB.head()

,book_id,title,authors
0,9780439785969,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré
1,9780439358071,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré
2,9780439554930,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré
3,9780439554893,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling
4,9780439655484,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré

# Penguin Events Data Extract/Transform

In [18]:
url = 'https://reststop.randomhouse.com/resources/authorevents/?start=0&max=0&expandLevel=1'

response = requests.get(url)

root = ET.fromstring(response.content)

In [19]:
for child in root.iter('*'):
    print(child.tag)
    break

authorevents

In [20]:
event_list = []

for child in root:
    event_list.append(child.attrib)

In [21]:
event_source = []
for i in event_list:
    event_source.append(i['uri'])

In [22]:
event_participants = []

for child in root:
    
    try:
        author = child.find('eventauthor').text
        event_participants.append(author)
    except:
        event_participants.append('none')
        print("no author")

no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author
no author

In [23]:
event_city = []

for child in root:
    
    try:
        city = child.find('city').text
        event_city.append(city)
    except:
        event_city.append('none')
        print("no city")

no city

In [24]:
event_date = []

for child in root:
    
    try:
        date = child.find('eventdate').text
        event_date.append(date)
    except:
        event_date.append('none')
        print("no date")

In [25]:
event_id = []

for child in root:
    
    try:
        ident = child.find('eventid').text
        event_id.append(ident)
    except:
        event_id.append('none')
        print("no id")

In [26]:
event_isbn = []

for child in root:
    
    try:
        isbn_numb = child.find('isbn').text
        event_isbn.append(isbn_numb)
    except:
        event_isbn.append('none')
        print("no isbn")

In [27]:
event_location = []

for child in root:
    
    try:
        location = child.find('location').text
        event_location.append(location)
    except:
        event_location.append('none')
        print("no loc")

no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc
no loc

In [28]:
event_market = []

for child in root:
    
    try:
        market = child.find('market').text
        event_market.append(market)
    except:
        event_market.append('none')
        print("no market")

no market

In [29]:
event_state = []

for child in root:
    
    try:
        state = child.find('state').text
        event_state.append(state)
    except:
        event_state.append('none')
        print("no state")

In [30]:
event_description = []

for child in root:
    
    try:
        description = child.find('description').text
        event_description.append(description)
    except:
        event_description.append('none')
        print("no description")

no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description
no description

In [31]:
table_events = pd.DataFrame(event_id)
table_events = table_events.rename(columns={0:'event_id'})
table_events.head()

  event_id
0    86905
1   195684
2   777615
3   875780
4   954952

In [37]:
table_events['event_source']=event_source
table_events['book_id']=event_isbn
table_events['event_participants']=event_participants
table_events['event_date']=event_date
table_events['event_location']=event_location
table_events['event_city']=event_city
table_events['event_state']=event_state
table_events['event_description']=event_description
table_events['event_market']=event_market

In [38]:
table_events['event_location']=table_events['event_location'].replace('\r\n','', regex=True)
table_events['event_source']=table_events['event_source'].replace('{','', regex=True)
table_events['book_id']=table_events['book_id'].astype(int)
table_events.dtypes

event_source          object
book_id                int64
event_participants    object
event_date            object
event_location        object
event_city            object
event_state           object
event_description     object
event_market          object
title                 object
authors               object
dtype: object

In [40]:

table_events = table_events.merge(booksDB, how='right', on='book_id')

In [41]:
table_events.head()

,event_source,book_id,event_participants,event_date,event_location,event_city,event_state,event_description,event_market,title_x,authors_x,title_y,authors_y
0,NaN,9780439785969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré
1,NaN,9780439358071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré
2,NaN,9780439554930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré
3,NaN,9780439554893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling
4,NaN,9780439655484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré

# Loading Data to Postgres

### Connecting to PostgreSQL

In [ ]:
# Karen's connection

# Connect to Postgres

#database = "booksETL"
#engine = create_engine('postgres://postgres:postgres@localhost:5432/booksETL')
#connection = engine.connect()

In [ ]:
#Andrea's connection

key = b'MOqEgKQI7nsUHaSoom2buW0Hy0qCvVDYaM1-Qp-Db5Q='
cipher_suite = Fernet(key)

with open('/Users/andreamorgan/Desktop/Encryptions_PG.bin', 'rb') as file_object:
    for line in file_object:
        encryptedpwd = line
        
uncipher_text = (cipher_suite.decrypt(encryptedpwd))
plain_text_encryptedpassword = bytes(uncipher_text).decode("utf-8") #convert to string

engine = create_engine(f'postgresql://postgres:{plain_text_encryptedpassword}@localhost:5432/booksETL')
connection = engine.connect()

In [ ]:
#Stacey's connection
# Deal with password needed for sql conn
#key = b'R_frnvbIOy25RMAXZtlk5yOn9x6m71YhQnfkpr2QM5w='
# cipher_suite = Fernet(key)

# with open('postgres.bin', 'rb') as file_object:
#     for line in file_object:
#         encryptedpwd = line
        
# uncipher_text = (cipher_suite.decrypt(encryptedpwd))
# pword = bytes(uncipher_text).decode("utf-8")

# engine = create_engine('postgresql://postgres:' + pword + '@localhost:5432/ETL')
# connection = engine.connect()
# engine.table_names()

### GOODREADS DATA LOAD

In [ ]:
# Confirm tables

engine.table_names()

In [ ]:
# Load titles into books table

booksDB.to_sql(name='books', con=engine, if_exists='append', index=False)

### NYT DATA LOAD

In [ ]:
#NYT DATA LOAD
# Dependent on the Goodreads/BooksDB section 

common_books = booksDB.merge(nyt_books,on=['book_id'])
common_books = common_books[['rank','weeks_on_list', 'book_id', 'publisher', 'book_review_link', 'category', 'current_as_of_date']]
common_books.index.name = 'reviews_id'

common_books.to_sql(name='reviews', con=engine, if_exists='append', index=True)

### PENGUIN EVENTS DATA LOAD

In [ ]:
table_events.to_sql(name='events', con = engine, if_exists = 'append', index=True)